name: soundscript
description: "Convert speech to text with Sound Script"

version: 0.1.1

environment:
  sdk: ^3.6.0
  flutter: 3.27.1

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_sound: ^9.28.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  http: ^1.3.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.2
  pwa_install: ^0.0.6
  share_plus: ^10.1.4
  speech_to_text: ^7.3.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true  
  assets:
    - assets/icon/icon.png
